---
name: Build and Push Container Images

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

permissions:
    actions: write
    contents: read

jobs:
  build-push-container-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
        fetch-depth: 0

      - uses: ./.github/actions/setup-dependencies
        with:
            install_task: "true"

      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@05340d1c670183e7caabdb33ae9f1c80fae3b0c2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a

      - name: Compute image Tag
        id: image-tag
        working-directory: app/
        shell: bash
        run: |
          version=$(task utils:generate-version -- "app")
          image_tag=$(task utils:generate-version-tag -- "app")
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "image_tag={image_tag}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: app/**
          push: ${{ env.ACT != 'true' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ steps.image-tag.outputs.image_tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
