# .github/workflows/ci-app.yaml
name: "CI: Application"

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  ci-checks:
    name: "Lint & Test Application"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt
          pip install flake8 pytest "httpx==0.27.2"

      - name: Lint with Flake8
        run: |
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Unit Tests
        run: |
          if [ -d "app/tests" ] && [ -n "$(find app/tests -name 'test_*.py')" ]; then
            echo "Running tests..."
            PYTHONPATH=app pytest app/tests/
          else
            echo "No tests found, skipping."
          fi

  snyk-security-scan:
    name: "Security Scan with Snyk"
    needs: [ci-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Snyk SAST & SCA Scan
        uses: snyk/actions/python-3.12@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=all
