# .github/workflows/ci-infra.yaml
name: "CI: Infrastructure"

on:
  workflow_call:
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true
      AWS_REGION:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  lint-terraform:
    name: "Lint Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: TFLint
        uses: tflint-github-action/tflint-github-action@v7
        with:
          tflint_working_dir: infra

  test-terraform-modules:
    name: "Test Terraform Modules"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['networking', 'acm', 'ecr', 'alb', 'ecs-fargate']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_CI_Infra_Test
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        # Use -backend=false to prevent any backend configuration or state locking
        run: terraform init -backend=false
        working-directory: infra/modules/${{ matrix.module }}/tests

      - name: Terraform Plan
        # Use -lock=false as an extra precaution
        run: terraform plan -lock=false
        working-directory: infra/modules/${{ matrix.module }}/tests
